version: "3.8"

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=pricey
      - POSTGRES_PASSWORD=pricey
      - POSTGRES_DB=pricey
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pricey"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  timescaledb_data:
